#!/usr/bin/env bash

let NIX_CONFIG = "/home/jaq/dots/dots/configuration.nix"
let HARDWARE_NIX_CONFIG = "/home/jaq/dots/dots/hardware-configuration.nix"

ln -sf $NIX_CONFIG /etc/nixos/ && echo "Symbolic link to 'configuration.nix' created at '/etc/nixos/' successfully."

if [ ! test -f $HARDWARE_NIX_CONFIG ]; then
    mv /etc/nixos/hardware-configuration.nix $HARDWARE_NIX_CONFIG
fi
