#################
### AUTOSTART ###
#################

exec-once = hypridle &
exec-once = systemctl --user start hyprpolkitagent &
exec-once = mako &
exec-once = swww-daemon &
exec-once = $HYPR_CONFIG/scripts/random-wall.sh &
exec-once = waybar &
