#################
### AUTOSTART ###
#################

# Set backup cursor config
exec-once = gsettings set org.gnome.desktop.interface cursor-theme BreezeX-RosePine-Linux
exec-once = gsettings set org.gnome.desktop.interface cursor-size 12

exec-once = hypridle
exec-once = hyprsunset
exec-once = systemctl --user start hyprpolkitagent

exec-once = mako
exec-once = udiskie
exec-once = swww-daemon

exec-once = /home/jaq/dots/dots/.config/hypr/scripts/random-wall.sh
exec-once = waybar
exec-once = $terminal -e $shell -e microfetch
