# import modules
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/inputs.conf
source = ~/.config/hypr/modules/looks.conf
source = ~/.config/hypr/modules/rules.conf
source = ~/.config/hypr/modules/autostart.conf

ecosystem {
    no_update_news      = true
    no_donation_nag     = true
}

misc {
    disable_hyprland_logo   = true
    force_default_wallpaper = 0
    vfr                     = true
}
