library_tabs = ["albums", "playlists", "tracks"]
use_nerdfont = true

[track_format]
    center           = ""
    left             = "%artists"
    right            = "%title"
    statusbar_format = "%artists  |  %title  |  %album"

[theme]
    background         = "#26233a"
    cmdline            = "#9ccfd8"
    cmdline_bg         = "#393552"
    error              = "#eb6f92"
    error_bg           = "#393552"
    highlight          = "#f6c177"
    highlight_bg       = "#393552"
    playing            = "#3e8fb0"
    playing_bg         = "#393552"
    playing_selected   = "#9ccfd8"
    primary            = "#c4a7e7"
    search_match       = "#eb6f92"
    secondary          = "#3e8fb0"
    statusbar          = "#9ccfd8"
    statusbar_bg       = "#3e8fb0"
    statusbar_progress = "#f6c177"
    title              = "#ea9a97"
