#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

# Set backup cursor config
exec-once = gsettings set org.gnome.desktop.interface cursor-theme BreezeX-RosePine-Linux
exec-once = gsettings set org.gnome.desktop.interface cursor-size 12

# Set random wallpaper
exec-once = swww-daemon
exec-once = swww img $(find /home/jaq/pics/wallpapers -type f -print0 | shuf --random-source=/dev/urandom -z -n 1 | tr -d '\0')

# Start auth agent
exec-once = systemctl --user start hyprpolkitagent

exec-once = waybar
exec-once = mako
exec-once = udiskie
