# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

source = ~/.config/hypr/env.conf

source = ~/.config/hypr/inputs.conf
source = ~/.config/hypr/looks.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/screens.conf

source = ~/.config/hypr/autostart.conf

# ###################
# ### PERMISSIONS ###
# ###################

# # See https://wiki.hyprland.org/Configuring/Permissions/
# # Please note permission changes here require a Hyprland restart
# # and are not applied on-the-fly for security reasons.

ecosystem {
    # enforce_permissions = 1
    no_update_news = true
    no_donation_nag = true
}

# # permission = /usr/(bin|local/bin)/grim, screencopy, allow
# # permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# # permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
