format = """
[░▒▓](#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
[](fg:#212736 bg:#1d2230)\
$time\
[](fg:#1d2230)\
\n$character\
"""

[character]
    format         = "$symbol "
    success_symbol = "[ ●](fg:#a3aed2)"
    error_symbol   = "[ ■](fg:#a3aed2)"

[directory]
    truncation_length = 6
    truncate_to_repo  = false
    truncation_symbol = "   "
    style             = "fg:#e3e5e5 bg:#769ff0"
    format            = "[ $path ]($style)"

    [directory.substitutions]
        "~/.config"       = "  "
        "~/Documents/dev" = " 󰲋 "
        "~/Documents"     = " 󰈙 "
        "~/Downloads"     = "  "
        "~/Music"         = " 󰝚 "
        "~/Pictures/pics" = "  "
        "~/Pictures"      = "  "
        "~"               = " 󰜥 "
        "/home"           = "  "
        "/"               = "  "

[git_branch]
    symbol = ""
    style  = "fg:#769ff0 bg:#394260"
    format = "[[ $symbol $branch ]($style)]($style)"

[git_status]
    ahead    = ""
    behind   = ""
    deleted  = "✖"
    diverged = ""
    renamed  = ""
    staged   = "✚"
    style    = "fg:#769ff0 bg:#394260"
    format   = "[[($all_status$ahead_behind )]($style)]($style)"

[time]
    disabled    = false
    style       = "fg:#a0a9cb bg:#1d2230"
    time_format = "%R"
    format      = "[[ $time ]($style)]($style)"
