library_tabs = ["albums", "playlists", "tracks"]
use_nerdfont = true

[track_format]
    center           = ""
    left             = "%artists"
    right            = "%title"
    statusbar_format = "%artists  |  %title  |  %album"

[theme]
    background         = "black"
    cmdline            = "light white"
    cmdline_bg         = "black"
    error              = "light white"
    error_bg           = "red"
    highlight          = "light white"
    highlight_bg       = "#484848"
    playing            = "green"
    playing_bg         = "black"
    playing_selected   = "light green"
    primary            = "light white"
    search_match       = "light red"
    secondary          = "light black"
    statusbar          = "black"
    statusbar_bg       = "green"
    statusbar_progress = "green"
    title              = "green"
