general.import = ["rose-pine-moon.toml"]

[window]
    opacity = 0.75

[font]
    normal = { family = "MesloLGMNerdFontMono", style = "Regular" }
    size   = 12

[env]
    SHELL = "/run/current-system/sw/bin/nu"
