[default.files]
"configs/nu/aliases.nu" = "~/.config/nushell/aliases.nu"
"configs/nu/cmds.nu" = "~/.config/nushell/cmds.nu"
"configs/nu/config.nu" = "~/.config/nushell/config.nu"
"configs/nu/env.nu" = "~/.config/nushell/env.nu"
"configs/cargo" = "~/.cargo/config.toml"
"configs/gitconfig" = "~/.gitconfig"
"configs/gitmessage" = "~/.gitmessage"
"configs/ncspot" = "~/.config/ncspot/config.toml"
"configs/starship" = "~/.config/starship.toml"
"configs/vscode" = "~/.config/Code/User/settings.json"

[settings]
default_target_type = "automatic"
