[default.files]
    "configs/alacritty"      = "~/.alacritty.toml"
    "configs/cargo"          = "~/.cargo/config.toml"
    "configs/gitconfig"      = "~/.gitconfig"
    "configs/gitmessage"     = "~/.gitmessage"
    "configs/hypr/hyprland"  = "~/.config/hypr/hyprland.conf"
    "configs/hypr/hyprpaper" = "~/.config/hypr/hyprpaper.conf"
    "configs/ncspot"         = "~/.config/ncspot/config.toml"
    "configs/nix"            = "/etc/nixos/configuration.nix"
    "configs/nu/aliases"     = "~/.config/nushell/aliases.nu"
    "configs/nu/cmds"        = "~/.config/nushell/cmds.nu"
    "configs/nu/config"      = "~/.config/nushell/config.nu"
    "configs/nu/env"         = "~/.config/nushell/env.nu"
    "configs/starship"      = "~/.config/starship.toml"
    "configs/vscode"        = "~/.config/Code/User/settings.json"

[settings]
    default_target_type = "automatic"
