[default.files]
    "dotfiles/alacritty/alacritty.toml"      = "~/.config/alacritty/alacritty.toml"
    "dotfiles/alacritty/rose-pine.toml"      = "~/.config/alacritty/rose-pine.toml"
    "dotfiles/alacritty/rose-pine-dawn.toml" = "~/.config/alacritty/rose-pine-dawn.toml"
    "dotfiles/alacritty/rose-pine-moon.toml" = "~/.config/alacritty/rose-pine-moon.toml"

    "dotfiles/btop/btop.conf"                   = "~/.config/btop/btop.conf"
    "dotfiles/btop/themes/rose-pine.theme"      = "~/.config/btop/themes/rose-pine.theme"
    "dotfiles/btop/themes/rose-pine-dawn.theme" = "~/.config/btop/themes/rose-pine-dawn.theme"
    "dotfiles/btop/themes/rose-pine-moon.theme" = "~/.config/btop/themes/rose-pine-moon.theme"

    "dotfiles/code/settings.json" = "~/.config/Code/User/settings.json"

    "dotfiles/fish/config.fish"                 = "~/.config/fish/config.fish"
    "dotfiles/fish/themes/rose-pine.theme"      = "~/.config/fish/themes/rose-pine.theme"
    "dotfiles/fish/themes/rose-pine-dawn.theme" = "~/.config/fish/themes/rose-pine-dawn.theme"
    "dotfiles/fish/themes/rose-pine-moon.theme" = "~/.config/fish/themes/rose-pine-moon.theme"

    "dotfiles/git/config" = "~/.config/git/config"

    "dotfiles/hypr/hyprland.conf" = "~/.config/hypr/hyprland.conf"
    "dotfiles/hypr/hypridle.conf" = "~/.config/hypr/hypridle.conf"
    "dotfiles/hypr/hyprlock.conf" = "~/.config/hypr/hyprlock.conf"

    "dotfiles/hypr/modules/autostart.conf" = "~/.config/hypr/modules/autostart.conf"
    "dotfiles/hypr/modules/env.conf"       = "~/.config/hypr/modules/env.conf"
    "dotfiles/hypr/modules/inputs.conf"    = "~/.config/hypr/modules/inputs.conf"
    "dotfiles/hypr/modules/looks.conf"     = "~/.config/hypr/modules/looks.conf"
    "dotfiles/hypr/modules/rules.conf"     = "~/.config/hypr/modules/rules.conf"

    "dotfiles/hypr/scripts/focus.sh"       = "~/.config/hypr/scripts/focus.sh"
    "dotfiles/hypr/scripts/random-wall.sh" = "~/.config/hypr/scripts/random-wall.sh"

    "dotfiles/hypr/themes/rose-pine.conf"      = "~/.config/hypr/themes/rose-pine.conf"
    "dotfiles/hypr/themes/rose-pine-dawn.conf" = "~/.config/hypr/themes/rose-pine-dawn.conf"
    "dotfiles/hypr/themes/rose-pine-moon.conf" = "~/.config/hypr/themes/rose-pine-moon.conf"

    "dotfiles/mako/rose-pine-moon.theme" = "~/.config/mako/config"

    "dotfiles/qBittorrent/qBittorrent.conf"              = "~/.config/qBittorrent/qBittorrent.conf"
    "dotfiles/qBittorrent/themes/rose-pine.qbtheme"      = "~/.config/qBittorrent/themes/rose-pine.qbtheme"
    "dotfiles/qBittorrent/themes/rose-pine-dawn.qbtheme" = "~/.config/qBittorrent/themes/rose-pine-dawn.qbtheme"
    "dotfiles/qBittorrent/themes/rose-pine-moon.qbtheme" = "~/.config/qBittorrent/themes/rose-pine-moon.qbtheme"

    "dotfiles/rofi/config.rasi"                = "~/.config/rofi/config.rasi"
    "dotfiles/rofi/themes/rose-pine.rasi"      = "~/.config/rofi/themes/rose-pine.rasi"
    "dotfiles/rofi/themes/rose-pine-dawn.rasi" = "~/.config/rofi/themes/rose-pine-dawn.rasi"
    "dotfiles/rofi/themes/rose-pine-moon.rasi" = "~/.config/rofi/themes/rose-pine-moon.rasi"

    "dotfiles/starship/starship.toml" = "~/.config/starship.toml"

    "dotfiles/waybar/config.jsonc"       = "~/.config/waybar/config.jsonc"
    "dotfiles/waybar/rose-pine.css"      = "~/.config/waybar/rose-pine.css"
    "dotfiles/waybar/rose-pine-dawn.css" = "~/.config/waybar/rose-pine-dawn.css"
    "dotfiles/waybar/rose-pine-moon.css" = "~/.config/waybar/rose-pine-moon.css"
    "dotfiles/waybar/style.css"          = "~/.config/waybar/style.css"

[settings]
    default_target_type = "automatic"
