"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$time\n\
$character\
"""

palette = "rose-pine-moon"

[palettes.rose-pine-moon]
    foam    = '#9ccfd8'
    gold    = '#f6c177'
    iris    = '#c4a7e7'
    love    = '#eb6f92'
    overlay = '#393552'
    pine    = '#3e8fb0'
    rose    = '#ea9a97'

[character]
    error_symbol   = "[ 󱞪](bold fg:love)"
    format         = " $symbol "
    success_symbol = "[ 󱞪](bold fg:iris)"

[directory]
    format            = "[](fg:overlay)[ $path ]($style)[](fg:overlay) "
    style             = "bg:overlay fg:pine"
    truncation_length = 3
    truncation_symbol = "…/"

    [directory.substitutions]
        "~/.config"   = ""
        "~/Downloads" = ""
        "~/dev"       = "󰲋"
        "~/docs"      = "󰈙"
        "~/pics"      = ""
        "/"           = " / "

[fill]
    style  = "fg:overlay"
    symbol = " "

[git_branch]
    format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
    style  = "bg:overlay fg:foam"
    symbol = ""

[git_status]
    ahead      = '[\(${count}\)](bg:overlay fg:foam)'
    behind     = '[\(${count}\)](bg:overlay fg:rose)'
    deleted    = '[×\($count\) ](style)'
    disabled   = false
    diverged   = '[\[](bg:overlay fg:iris)[\(${ahead_count}\)](bg:overlay fg:foam)[\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
    format     = '[](fg:overlay)([$all_status$ahead_behind]($style))[](fg:overlay)'
    modified   = '[!\($count\) ](bg:overlay fg:gold)'
    renamed    = '[\($count\) ](bg:overlay fg:iris)'
    staged     = '[+\($count\) ](bg:overlay fg:gold)'
    stashed    = '[\$](bg:overlay fg:iris)'
    style      = "bold bg:overlay fg:love"
    untracked  = '[?\($count\) ](bg:overlay fg:gold)'
    up_to_date = '[✓](bg:overlay fg:iris)'

[time]
    disabled    = false
    format      = " [](fg:overlay)[ $time 󰧱 ]($style)[▓▒░](fg:overlay)"
    style       = "bg:overlay fg:rose"
    time_format = "%I:%M%P"
    use_12hr    = true

[username]
    disabled    = false
    format      = "[░▒▓](fg:overlay)[ 󰧱 $user ]($style)[](fg:overlay) "
    show_always = true
    style_root  = "bg:overlay fg:love"
    style_user  = "bg:overlay fg:iris"
