"$schema" = 'https://starship.rs/config-schema.json'

##################################################################
###################### Prompt Configuration ######################
##################################################################

format = """
[░▒▓](red)\
$os\
$username\
[](bg:peach fg:red)\
$directory\
[](bg:yellow fg:peach)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$c\
$cpp\
$rust\
$java\
$python\
[](fg:green bg:sapphire)\
$cmd_duration\
[](fg:sapphire bg:lavender)\
$time\
[ ](fg:lavender)\
$line_break\
$character
"""

palette = "frappe"

[character]
    error_symbol   = "[ ■](bold fg:red)"
    format         = "$symbol "
    success_symbol = "[ ●](bold fg:green)"

[cmd_duration]
    disabled          = false
    format            = "[ $duration ]($style)"
    min_time          = 5
    show_milliseconds = true
    style             = "fg:crust bg:sapphire"

[directory]
    format            = "[ $path ]($style)"
    read_only         = " 󰌾"
    style             = "bold fg:crust bg:peach"
    truncation_symbol = "/"

    [directory.substitutions]
        "/"         = " / "
        "~/.config" = ""
        "~/dev"     = "󰲋"
        "~/docs"    = "󰈙"
        "~/dwnlds"  = ""
        "~/pics"    = ""

[git_branch]
    format = '[ $symbol $branch ]($style)'
    style  = "fg:crust bg:yellow"
    symbol = ""

[git_status]
    ahead    = ""
    behind   = ""
    deleted  = "×"
    diverged = ""
    format   = '[($all_status$ahead_behind )]($style)'
    renamed  = ""
    staged   = "+"
    style    = "bold fg:crust bg:yellow"

[os]
    disabled = false
    style    = "bg:red fg:crust"

[time]
    disabled    = false
    format      = '[  $time ]($style)'
    style       = "fg:crust bg:lavender"
    time_format = "%R"

[username]
    format      = '[$user ]($style)'
    show_always = true
    style_root  = "bold bg:red fg:crust"
    style_user  = "bg:red fg:crust"

    ##################################################################
    ############################# Icons ##############################
    ##################################################################

[aws]
    symbol = "  "

[buf]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[bun]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[c]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[cpp]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[cmake]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[cobol]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"

[conda]
    symbol = "  "

[crystal]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[daml]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"

[dart]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[deno]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[dotnet]
    format = "[$symbol($version )]($style)"
    style  = "bold fg:crust bg:green"

[docker_context]
    symbol = "  "

[elixir]
    format = '[$symbol($version \(OTP $otp_version\) )]($style)'
    style  = "bold fg:crust bg:green"
    symbol = "  "

[elm]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[erlang]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"

[fennel]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[fossil_branch]
    symbol = "  "

[gcloud]
    symbol = "   "

[git_commit]
    tag_symbol = "  "

[gleam]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"

[golang]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[gradle]
    symbol = "  "

[guix_shell]
    symbol = "  "

[haskell]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[haxe]
    symbol = "  "

[helm]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"

[hg_branch]
    symbol = "  "

[hostname]
    ssh_symbol = "  "

[java]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[julia]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[kotlin]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[lua]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[memory_usage]
    symbol = " 󰍛 "

[meson]
    symbol = " 󰔷 "

[nim]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = " 󰆥 "

[nix_shell]
    symbol = "  "

[nodejs]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[ocaml]
    format = '$symbol($version )(\($switch_indicator$switch_name\) )]($style)'
    style  = "bold fg:crust bg:green"
    symbol = "  "

[opa]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"

    [os.symbols]
        AlmaLinux        = "  "
        Alpaquita        = "  "
        Alpine           = "  "
        Amazon           = "  "
        Android          = "  "
        Arch             = "  "
        Artix            = "  "
        CachyOS          = "  "
        CentOS           = "  "
        Debian           = "  "
        DragonFly        = "  "
        Emscripten       = "  "
        EndeavourOS      = "  "
        Fedora           = "  "
        FreeBSD          = "  "
        Garuda           = " 󰛓 "
        Gentoo           = " 󰣨 "
        HardenedBSD      = " 󰞌 "
        Illumos          = " 󰈸 "
        Kali             = "  "
        Linux            = "  "
        Mabox            = "  "
        Macos            = "  "
        Manjaro          = "  "
        Mariner          = "  "
        MidnightBSD      = "  "
        Mint             = " 󰣭 "
        NetBSD           = "  "
        NixOS            = "  "
        Nobara           = "  "
        OpenBSD          = " 󰈺 "
        OracleLinux      = " 󰌷 "
        Pop              = "  "
        Raspbian         = "  "
        RedHatEnterprise = "  "
        Redhat           = "  "
        Redox            = " 󰀘 "
        RockyLinux       = "  "
        SUSE             = "  "
        Solus            = " 󰠳 "
        Ubuntu           = "  "
        Unknown          = "  "
        Void             = "  "
        Windows          = " 󰍲 "
        openSUSE         = "  "

[package]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = " 󰏗 "

[perl]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[php]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[pijul_channel]
    symbol = "  "

[pixi]
    symbol = " 󰏗 "

[purescript]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"

[python]
    format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
    style  = "bold fg:crust bg:green"
    symbol = "  "

[quarto]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"

[raku]
    format = "[$symbol($version-$vm_version )]($style)"
    style  = "bold fg:crust bg:green"

[red]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"

[rlang]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = " 󰟔 "

[ruby]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[rust]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = " 󱘗 "

[scala]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[swift]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

[typst]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"

[vagrant]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"

[vlang]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"

[zig]
    format = "[$symbol$version ]($style)"
    style  = "bold fg:crust bg:green"
    symbol = "  "

    ##################################################################
    ######################### Color Palettes #########################
    ##################################################################

[palettes.custom]
    bg1 = "#769ff0"
    bg2 = "#394260"
    bg3 = "#212736"
    bg4 = "#1d2230"
    fg1 = "#d3d6ec"
    fg2 = "#a0a9cb"

[palettes.mocha]
    base      = "#1e1e2e"
    blue      = "#89b4fa"
    crust     = "#11111b"
    flamingo  = "#f2cdcd"
    green     = "#a6e3a1"
    lavender  = "#b4befe"
    mantle    = "#181825"
    maroon    = "#eba0ac"
    mauve     = "#cba6f7"
    overlay0  = "#6c7086"
    overlay1  = "#7f849c"
    overlay2  = "#9399b2"
    peach     = "#fab387"
    pink      = "#f5c2e7"
    red       = "#f38ba8"
    rosewater = "#f5e0dc"
    sapphire  = "#74c7ec"
    sky       = "#89dceb"
    subtext0  = "#a6adc8"
    subtext1  = "#bac2de"
    surface0  = "#313244"
    surface1  = "#45475a"
    surface2  = "#585b70"
    teal      = "#94e2d5"
    text      = "#cdd6f4"
    yellow    = "#f9e2af"

[palettes.frappe]
    base      = "#303446"
    blue      = "#8caaee"
    crust     = "#232634"
    flamingo  = "#eebebe"
    green     = "#a6d189"
    lavender  = "#babbf1"
    mantle    = "#292c3c"
    maroon    = "#ea999c"
    mauve     = "#ca9ee6"
    overlay0  = "#737994"
    overlay1  = "#838ba7"
    overlay2  = "#949cbb"
    peach     = "#ef9f76"
    pink      = "#f4b8e4"
    red       = "#e78284"
    rosewater = "#f2d5cf"
    sapphire  = "#85c1dc"
    sky       = "#99d1db"
    subtext0  = "#a5adce"
    subtext1  = "#b5bfe2"
    surface0  = "#414559"
    surface1  = "#51576d"
    surface2  = "#626880"
    teal      = "#81c8be"
    text      = "#c6d0f5"
    yellow    = "#e5c890"

[palettes.latte]
    base      = "#eff1f5"
    blue      = "#1e66f5"
    crust     = "#dce0e8"
    flamingo  = "#dd7878"
    green     = "#40a02b"
    lavender  = "#7287fd"
    mantle    = "#e6e9ef"
    maroon    = "#e64553"
    mauve     = "#8839ef"
    overlay0  = "#9ca0b0"
    overlay1  = "#8c8fa1"
    overlay2  = "#7c7f93"
    peach     = "#fe640b"
    pink      = "#ea76cb"
    red       = "#d20f39"
    rosewater = "#dc8a78"
    sapphire  = "#209fb5"
    sky       = "#04a5e5"
    subtext0  = "#6c6f85"
    subtext1  = "#5c5f77"
    surface0  = "#ccd0da"
    surface1  = "#bcc0cc"
    surface2  = "#acb0be"
    teal      = "#179299"
    text      = "#4c4f69"
    yellow    = "#df8e1d"

[palettes.macchiato]
    base      = "#24273a"
    blue      = "#8aadf4"
    crust     = "#181926"
    flamingo  = "#f0c6c6"
    green     = "#a6da95"
    lavender  = "#b7bdf8"
    mantle    = "#1e2030"
    maroon    = "#ee99a0"
    mauve     = "#c6a0f6"
    overlay0  = "#6e738d"
    overlay1  = "#8087a2"
    overlay2  = "#939ab7"
    peach     = "#f5a97f"
    pink      = "#f5bde6"
    red       = "#ed8796"
    rosewater = "#f4dbd6"
    sapphire  = "#7dc4e4"
    sky       = "#91d7e3"
    subtext0  = "#a5adcb"
    subtext1  = "#b8c0e0"
    surface0  = "#363a4f"
    surface1  = "#494d64"
    surface2  = "#5b6078"
    teal      = "#8bd5ca"
    text      = "#cad3f5"
    yellow    = "#eed49f"
