name: formatter

on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    name: run alejandra
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
      - run: nix run nixpkgs#alejandra -- -q -c .
